item_values:
  # CURRENCY
  GOLD_COIN: 1
  GOLD_BAR: 64
  GOLD_BLOCK: 4096
  ROYAL_GOLD_BLOCK: 262144

  # GENERAL
  GLASS_BOTTLE: 1

  # BEACH
  DRIFTWOOD: 1
  TROPICAL_FISH: 1
  SEASHELL: 4
  SHARK_TOOTH: 10
  CURSED_BONE: 25
  PIRATE_GOLD: 128

  SHELL_HELMET: 15
  SHELL_CHESTPLATE: 24
  SHELL_LEGGINGS: 21
  SHELL_BOOTS: 12
  SHELL_SWORD: 6
  SHELL_TALISMAN: 24

  PIRATE_CLOTH: 15
  PIRATE_HELMET: 56
  PIRATE_CHESTPLATE: 90
  PIRATE_LEGGINGS: 78
  PIRATE_BOOTS: 45
  PIRATE_CUTLASS: 150
  CAPTAIN_HAT: 150
  PIRATE_ROD: 150

  SHARK_TOOTH_SWORD: 15

  # OCEAN
  SEAWEED: 1
  ATLANTIC_SALMON: 2
  RAINBOW_TROUT: 6
  PEARL: 15
  CORAL_FRAGMENT: 35
  MERMAID_SCALE: 200
  MEGALODON_TOOTH: 1600

  SUNKEN_SCRAP: 25
  DROWNED_HELMET: 93
  DROWNED_CHESTPLATE: 150
  DROWNED_LEGGINGS: 131
  DROWNED_BOOTS: 75
  CROWN_OF_THE_DAMNED: 2000

  MEGALODON_TOOTH_SPEAR: 601

  # JUNGLE
  VINES: 1
  OLD_COD: 2
  PUFFERFISH: 7
  BLOODFIN_PIRANHA: 20
  SERPENT_SCALES: 50
  VERDANT_EMERALD: 300
  TOTEM_OF_THE_JAGUAR: 2500
  GOLDEN_IDOL: 5000

  SPIRIT_ESSENCE: 45
  VOODOO_MASK: 168
  VOODOO_CHESTPLATE: 270
  VOODOO_LEGGINGS: 236
  VOODOO_BOOTS: 135

  # ARCTIC
  ICE_TROUT: 1
  SNOW_CRAB: 10
  PENGUIN_EGG: 30
  FROZEN_SKULL: 120
  FROSTED_ANTLER: 480
  GLACIAL_RUNE: 3000
  JOTUN_ICE_CORE: 16000

  # VOID
  VOID_FISH: 3

  # CHERRY
  PINK_SPLASHER: 3
  PINK_TULIP: 3
  CHERRY_FRUIT: 3
  SAKURA_LEAVES: 3
  CHERRY_CRYSTAL: 3
  SPRINGVEIL_BUD: 3
  SPRINGVEIL_BLOSSOM: 3

  TURTLE_SHELL: 8
  KRAKEN_INK: 32
